Lab 1
Brahialis0209/gpu_labs pull request #1
Opened 2022-03-28 19:35 UTC by Brahialis0209

Первая лабораторная работа готова, проверьте пожалуйста.

2022-03-30 10:15 UTC, anthark requested changes
У вас приложение запускается только из под VS, а если просто ткнуть на .exe файл - не работает. Но требование по задачам - чтобы работало при таком запуске, это нужно для удобной настройки RenderDoc

К конкретному этому заданию требовалось еще добавить имена для ресурсов и метки выполнения

2022-03-30 10:15 UTC, anthark commented on lab1/main.cpp
> +    if (arg_count != 0){ if (args[0] == L"DEBUG"){ l_debug = true; } }
Некорректное сравнение строк, l_debug так никогда не станет true

2022-03-30 19:02 UTC, Brahialis0209 commented
> У вас приложение запускается только из под VS, а если просто ткнуть на .exe файл - не работает. Но требование по задачам - чтобы работало при таком запуске, это нужно для удобной настройки RenderDoc
> 
> К конкретному этому заданию требовалось еще добавить имена для ресурсов и метки выполнения

Исправил, проверьте пожалуйста

2022-03-31 09:48 UTC, anthark approved these changes

2022-03-31 09:48 UTC, anthark commented
Хорошо, молодцы - все работает. Задача засчитана.

2022-03-31 09:48 UTC, merged