Lab 2
Brahialis0209/gpu_labs pull request #2
Opened 2022-04-28 21:39 UTC by AgalakovDV

2022-04-29 12:30 UTC, anthark requested changes
Вроде, все работает, если удается скомпилировать и запустить. У меня начисто взятая версия не компилируется из-за того, что не указаны тип и профиль шейдеров в проекте. Исправьте, пожалуйста.

2022-04-30 11:21 UTC, Brahialis0209 commented
> Например, все работает, если экспорт компилировать и воспроизводить. У меня начисто взятая версия не компилируется из-за того, что не указан тип и профиль шейдеров в проекте. Исправьте, пожалуйста.

Действительно были проблемы при сборке и запуске начисто взятого проекта, теперь кажется исправили и проблем быть не должно. Проверьте пожалуйста.

2022-05-04 15:26 UTC, anthark commented
> > Например, все работает, если экспорт компилировать и воспроизводить. У меня начисто взятая версия не компилируется из-за того, что не указан тип и профиль шейдеров в проекте. Исправьте, пожалуйста.
> 
> Действительно были проблемы при сборке и запуске начисто взятого проекта, теперь кажется исправили и проблем быть не должно. Проверьте пожалуйста.

По-моему, стало хуже =(

В sln файле поехал путь к проекту lab_2. Он теперь не открывается, если не исправить. 
И hlsl файлы в проекте, как не компилировались, так и не компилируются. Им нужно в свойствах установить, какой это тип шейдера (вершинный, пиксельный) и модель языка (у нас 5.0)

2022-05-04 15:27 UTC, anthark requested changes
Все равно не компилируется

2022-05-04 16:05 UTC, Brahialis0209 commented
> > > Например, все работает, если экспорт компилировать и включать. У меня начисто взятая версия не компилируется из-за того, что не указан тип и профиль шейдеров в проекте. Исправьте, пожалуйста.
> > 
> > 
> > Действительно были проблемы при сборке и выявлении начисто взятого проекта, теперь кажется исправили и проблем быть не должно. Используйте пожалуйста.
> 
> По-моему, стало хуже =(
> 
> В sln файле поехал путь к проекту lab_2. Он теперь не открывается, если не исправить. И hlsl файлы в проекте, как не компилировались, так и не компилируются. Им нужно в свойствах установить, какой это тип шейдера (вершинный, пиксельный) и модель языка (у нас 5.0)

Извините, путь к проекту был не валидным; hlsl файлы кажется, теперь компилируются. Проверьте пожалуйста.

2022-05-04 16:15 UTC, anthark approved these changes

2022-05-04 16:15 UTC, anthark commented
Да, теперь все работает. Задача засчитана.

2022-05-04 16:15 UTC, merged